webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    # output_path: false

    script_attributes:
        defer: true
        'data-turbo-track': reload
    link_attributes:
        'data-turbo-track': reload

    crossorigin: 'anonymous'
    preload: true
    cache: false

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

when@prod:
    webpack_encore:
        cache: true
        strict_mode: false

when@test:
    webpack_encore:
        cache: false
        strict_mode: false
