twig:
    form_themes:
        - '@DevscastDashlite/layout/form_theme.html.twig'
    default_path: '%kernel.project_dir%/templates'
    date:
        format: 'd M Y'
        interval_format: '%d jours restants'
        timezone: null
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'

when@test:
    twig:
        strict_variables: true
