webpack_encore:
    output_path: '%kernel.project_dir%/public/assets'

    script_attributes:
        defer: true
        'data-turbo-track': reload
    link_attributes:
        'data-turbo-track': reload
    crossorigin: 'anonymous'
    preload: true
    strict_mode: true
    cache: false

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'

when@prod:
    webpack_encore:
        cache: true
        strict_mode: false

when@test:
    webpack_encore:
        cache: false
        strict_mode: false
