name: Update Flex endpoint

on:
    push:
        branches:
            - main

permissions:
    contents: read

defaults:
    run:
        shell: bash

jobs:
    call-flex-update:
        uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main
        with:
            contrib: true